version: '2'
services:
  cache_redis:
    image: redis:alpine
    expose: 
      - 6379
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  crawler-service:
    build: ./crawler-service
    volumes:
      - ./crawler-service:/var/www/app
    ports:
      - 3332:3332
    command:
      sh -c 'npm i && node server.js'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  manage-queue:
    links:
      - cache_redis
    build: ./manage-queue-service
    volumes:
      - ./manage-queue-service:/var/www/app
    ports:
      - 3331:3331
    command:
      sh -c 'npm i && node src/server.js && node src/queue.js'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  api-getway:
    links:
      - manage-queue
      - crawler-service
    build: ./api-getway
    volumes:
      - ./api-getway:/var/www/app
    ports:
      - 4200:4200
    command:
      sh -c 'npm i && node index.js'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1