version: '3'
services:
  redis:
    image: redis:alpine
    container_name: cache_redis
    expose:
      - 6379

  crawler-service:
    build: ./crawler-service
    volumes:
      - ./crawler-service:/var/www/app
    ports:
      - 3332:3332
    command:
      sh -c 'npm i && node server.js'

  manage-queue:
    links:
      - redis
    build: ./manage-queue-service
    volumes:
      - ./manage-queue-service:/var/www/app
    ports:
      - 3331:3331
    command:
      sh -c 'npm i && node src/server.js && src/node queue.js'

  api-getway:
    links:
      - manage-queue
      - crawler-service
    build: ./api-getway
    volumes:
      - ./api-getway:/var/www/app
    ports:
      - 4200:4200
    command:
      sh -c 'npm i && node index.js'